### ISSUE TITLE
Federated match completion

### ISSUE THREAD

**Issue by youngbrioche** [innoq/iqvoc#268]
There should be an autocompleted suggestion list for text inputs when a user wants to assign a match to a concept in a linked iQvoc instance.
## ToDo
- [x] Configuration (for now we're using the existing config for federated search)
- [ ] ~~Enhance EntitySelector~~
- [x] Proxy for alphabetical search resource
- [x] Client side components: `ConceptMapping` and `ConceptMappingManager`
- [x] Async loading of pref labels for matches
- [ ] ~~Loading indicators for labels~~
- [x] Styling of mapping bubbles
- [ ] ~~Rewrite in CoffeeScript (with separate (generic?) component for dealing with CSV in text areas)~~
- [x] Loading indicator for autocomplete
- [ ] Deal with localized alphabetical_concepts resource (autocompletion)
## Refactoring
- [ ] replace Faraday
- [x] move `datasets_as_json` to concern mix-in
